# Generated by Django 3.1.1 on 2021-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prenoms',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
