# Generated by Django 3.1.1 on 2021-03-06 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('marque', models.CharField(max_length=200, null=True)),
                ('caracteristique', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('type_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiels.categories')),
            ],
        ),
        migrations.CreateModel(
            name='TravauxDemande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('COURS', 'En cours'), ('FINI', 'Fini mais pas livré'), ('LIVRER', 'Fini et Livrer'), ('IMPOSSIBLE', 'Impossible')], max_length=50)),
                ('objet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('commentaire', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('materiel', models.ManyToManyField(to='materiels.Materiel')),
            ],
        ),
    ]
